/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/relay-proxy/wrangler.jsonc --include-runtime=false workers/relay-proxy/src/worker-configuration.d.ts` (hash: dd418e0400d2d5920d394b03d50abe24)
interface __BaseEnv_Env {
	ENTITLEMENTS: D1Database;
	ASSETS: Fetcher;
	EXPECTED_STRIPE_PAYMENT_LINK_ID: "plink_1TwaWm8BrcdmT7aM5jfn11nU";
	ORIGIN_URL: "https://2600-1900-4041-40e-0-1-0-0.sslip.io";
	PAID_MAX_GUESTS: "8";
	FIREBASE_PROJECT_ID: "silverfish-app";
	RELAY_PROXY_SECRET: string;
	STRIPE_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EXPECTED_STRIPE_PAYMENT_LINK_ID" | "ORIGIN_URL" | "PAID_MAX_GUESTS" | "FIREBASE_PROJECT_ID" | "RELAY_PROXY_SECRET" | "STRIPE_WEBHOOK_SECRET">> {}
}
