#!/usr/bin/env bash
# Build, notarize, verify, and deploy the managed Apple-silicon release.
# Required local material lives outside the repository in ~/.silverfish-signing.
set -euo pipefail

repo_root=$(cd "$(dirname "$0")/.." && pwd)
signing_dir=${SILVERFISH_SIGNING_DIR:-"$HOME/.silverfish-signing"}
secret_file="$signing_dir/github-secrets.txt"
p12_file="$signing_dir/developerID_application.p12"
api_key_file="$signing_dir/AuthKey_6KXLPBXVFV.p8"
updater_key_file="$signing_dir/tauri-updater.key"

# The repository's .env can hold a narrow automation token. Run deployment
# commands from outside the repository so Wrangler uses the interactive OAuth
# session with D1 and Workers write access instead.
wrangler_oauth() {
  (
    cd "${TMPDIR:-/tmp}"
    env -u CLOUDFLARE_API_TOKEN "$repo_root/node_modules/.bin/wrangler" "$@"
  )
}

for required in "$secret_file" "$p12_file" "$api_key_file" "$updater_key_file"; do
  [[ -f "$required" ]] || { echo "Missing release material: $required" >&2; exit 1; }
done

# Do not source this file: values such as the signing identity contain spaces
# and parentheses. Read only the allowlisted names without evaluating content.
read_secret() {
  local name=$1 value
  value=$(sed -n "s/^${name}=//p" "$secret_file" | head -n1)
  [[ -n "$value" ]] || { echo "Missing $name in $secret_file" >&2; exit 1; }
  printf '%s' "$value"
}
APPLE_CERTIFICATE_PASSWORD=$(read_secret APPLE_CERTIFICATE_PASSWORD)
APPLE_SIGNING_IDENTITY=$(read_secret APPLE_SIGNING_IDENTITY)
APPLE_TEAM_ID=$(read_secret APPLE_TEAM_ID)
APPLE_API_KEY=$(read_secret APPLE_API_KEY)
APPLE_API_ISSUER=$(read_secret APPLE_API_ISSUER)
KEYCHAIN_PASSWORD=$(read_secret KEYCHAIN_PASSWORD)
TAURI_SIGNING_PRIVATE_KEY_PASSWORD=$(security find-generic-password -a "$USER" -s "silverfish-tauri-updater-key" -w)

temp_dir=$(mktemp -d "${TMPDIR:-/tmp}/silverfish-release.XXXXXX")
keychain="$temp_dir/release.keychain-db"
pem_file="$temp_dir/developer-id.pem"
compatibility_p12="$temp_dir/developer-id-legacy.p12"
original_keychains=()
while IFS= read -r listed_keychain; do
  listed_keychain=${listed_keychain#*\"}
  listed_keychain=${listed_keychain%\"*}
  [[ -n "$listed_keychain" ]] && original_keychains+=("$listed_keychain")
done < <(security list-keychains -d user)
cleanup() {
  ((${#original_keychains[@]})) && security list-keychains -d user -s "${original_keychains[@]}" >/dev/null 2>&1 || true
  security delete-keychain "$keychain" >/dev/null 2>&1 || true
  rm -rf "$temp_dir"
}
trap cleanup EXIT

security create-keychain -p "$KEYCHAIN_PASSWORD" "$keychain"
security set-keychain-settings -lut 21600 "$keychain"
security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$keychain"
# macOS Security.framework cannot import the PBES2/AES export generated by
# recent OpenSSL versions. Repackage the verified local P12 only inside the
# temporary release directory with legacy-compatible encryption.
openssl pkcs12 -in "$p12_file" -passin "pass:$APPLE_CERTIFICATE_PASSWORD" -nodes -out "$pem_file"
openssl pkcs12 -export -legacy -in "$pem_file" -out "$compatibility_p12" -passout "pass:$APPLE_CERTIFICATE_PASSWORD"
security import "$compatibility_p12" -f pkcs12 -k "$keychain" -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" "$keychain"

export KEYCHAIN_PASSWORD
export APPLE_SIGNING_IDENTITY
export APPLE_TEAM_ID
export TAURI_SIGNING_PRIVATE_KEY="$updater_key_file"
export TAURI_SIGNING_PRIVATE_KEY_PASSWORD
export VITE_SILVERFISH_MANAGED_SERVICE=true
export VITE_SILVERFISH_RELAY_URL=$(gh variable get VITE_SILVERFISH_RELAY_URL --repo dmyoung1994/silverfish-cloud)
export VITE_SILVERFISH_SUBSCRIBE_URL=$(gh variable get VITE_SILVERFISH_SUBSCRIBE_URL --repo dmyoung1994/silverfish-cloud)
export VITE_FIREBASE_API_KEY=$(gh variable get VITE_FIREBASE_API_KEY --repo dmyoung1994/silverfish-cloud)
export VITE_GOOGLE_OAUTH_CLIENT_ID=$(gh variable get VITE_GOOGLE_OAUTH_CLIENT_ID --repo dmyoung1994/silverfish-cloud)
export VITE_GOOGLE_OAUTH_CLIENT_SECRET=$(gh variable get VITE_GOOGLE_OAUTH_CLIENT_SECRET --repo dmyoung1994/silverfish-cloud)

cd "$repo_root"
npm ci
security list-keychains -d user -s "$keychain" "${original_keychains[@]}"
npm --workspace apps/desktop run tauri -- build --target aarch64-apple-darwin
dmg=$(find target/aarch64-apple-darwin/release/bundle/dmg -name '*.dmg' -print -quit)
[[ -n "$dmg" ]] || { echo "Tauri did not create a DMG" >&2; exit 1; }
updater_bundle=$(find target/aarch64-apple-darwin/release/bundle/macos -name '*.app.tar.gz' -print -quit)
[[ -n "$updater_bundle" && -f "$updater_bundle.sig" ]] || { echo "Tauri did not create a signed updater bundle" >&2; exit 1; }

codesign --verify --deep --strict --verbose=2 "$dmg"
xcrun notarytool submit "$dmg" --key "$api_key_file" --key-id "$APPLE_API_KEY" --issuer "$APPLE_API_ISSUER" --wait --timeout 45m
xcrun stapler staple "$dmg"
xcrun stapler validate "$dmg"
spctl --assess --type open --context context:primary-signature -vv "$dmg"

mkdir -p apps/desktop/public/updates
release_version=$(node -p 'require("./apps/desktop/package.json").version')
release_tag="v${release_version}"
release_notes="Guest-to-host conversion funnel and automatic in-app updates."
public_repo=${SILVERFISH_PUBLIC_REPO:-dmyoung1994/silverfish}
if ! gh release view "$release_tag" --repo "$public_repo" >/dev/null 2>&1; then
  gh release create "$release_tag" --repo "$public_repo" --title "Silverfish v${release_version}" --notes "$release_notes"
fi
gh release upload "$release_tag" \
  "$dmg#Silverfish-macOS-arm64.dmg" \
  "$updater_bundle#Silverfish.app.tar.gz" \
  "$updater_bundle.sig#Silverfish.app.tar.gz.sig" \
  --repo "$public_repo" --clobber
node scripts/publish-updater-release.mjs \
  --version "$release_version" \
  --artifact "$updater_bundle" \
  --signature "$updater_bundle.sig" \
  --artifact-url "https://github.com/${public_repo}/releases/download/${release_tag}/Silverfish.app.tar.gz" \
  --notes "$release_notes" \
  --output-dir apps/desktop/public/updates
gh release upload "$release_tag" apps/desktop/public/updates/latest.json --repo "$public_repo" --clobber
shasum -a 256 "$dmg"
npm run build
wrangler_oauth d1 migrations apply silverfish-entitlements --remote --config "$repo_root/workers/relay-proxy/wrangler.jsonc"
wrangler_oauth deploy --config "$repo_root/workers/relay-proxy/wrangler.jsonc"
curl --fail --head "${SILVERFISH_DOWNLOAD_URL:-https://try.silverfish-app.workers.dev/downloads/Silverfish-macOS-arm64.dmg}"
curl --fail --header 'cache-control: no-cache' "${SILVERFISH_UPDATE_BASE_URL:-https://try.silverfish-app.workers.dev}/updates/latest.json"
